name: Test JWT Token Generation

on: 
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        id: jwt
        uses: atnyooehlenberg/github-action-livedemo-jwt@v0.2.4
        with:
          secret: '123456'
          issuer: 'jwt@testsystem'
          audience: 'jwt@testsystem'
          validDays: 7
          offline: 'YES'
          contact: 'test@testsystem.test'
          devenv: 'NO'        

      - name: Get Token
        run: echo "${{ steps.jwt.outputs.token }}"